name: AI PR Description

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened]

jobs:
  generate-description:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: coderabbitai/ai-pr-description@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
